locale:
  language:
    default: en

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

spring:
  application:
    name: shopping

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:ls}?currentSchema=shopping
    type: com.zaxxer.hikari.HikariDataSource
    username: ${DB_USERNAME:ls}
    password: ${DB_PASSWORD:ls}

  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        default_schema: shopping
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    schemas: shopping
    table: schema_version
    validate-on-migrate: false